name: Build and Test

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'
  release:
    types: [created]

jobs:
  observer_debug:
    name: Assemble Tazama Observer (debug)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
            cd observer
            echo "MAPS_API_KEY=none" >> local.properties
            ./gradlew assembleDebug

  test_observer:
    name: Test Tazama Observer
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Test
        run: |
            cd observer
            echo "MAPS_API_KEY=none" >> local.properties
            ./gradlew test

  libui:
    name: Build and test libui
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
            cd libui
            ./gradlew build
            ./gradlew test

  libvehicle:
    name: Build and test libvehicle
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
            cd libvehicle
            ./gradlew build
            ./gradlew test

