name: Build and Test

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'
  release:
    types: [created]

jobs:
  observer_debug:
    name: Assemble Tazama Observer (debug)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
            echo "MAPS_API_KEY=none" >> local.properties
            ./observer/gradlew assembleDebug

  test_observer:
    name: Test Tazama Observer
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Test
        run: |
            echo "MAPS_API_KEY=none" >> local.properties
            ./observer/gradlew test

