name: Build and Test

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'
  release:
    types: [created]

jobs:
  observer_debug:
    name: Assemble Tazama Observer (debug)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        working-directory: ./observer
        run: |
            touch local.properties
            ./gradlew assembleDebug

  test_observer:
    name: Test Tazama Observer
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Test
        working-directory: ./observer
        run: |
            touch local.properties
            ./gradlew test

  survey_debug:
    name: Assemble Tazama Survey (debug)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        working-directory: ./survey
        run: ./gradlew assembleDebug

  test_survey:
    name: Test Tazama Survey
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Test
        working-directory: ./survey
        run: ./gradlew test

  libui:
    name: Build and test libui
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        working-directory: ./libui
        run: |
            ./gradlew build
            ./gradlew test

  libvehicle:
    name: Build and test libvehicle
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        working-directory: ./libvehicle
        run: |
            ./gradlew build
            ./gradlew test

  libviewmodel:
    name: Build and test libviewmodel
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        working-directory: ./libviewmodel
        run: |
            ./gradlew build
            ./gradlew test

  maplibre-compose:
    name: Build and test maplibre-compose
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        working-directory: ./maplibre-compose
        run: |
            ./gradlew build
            ./gradlew test

